server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/ticket_booking_system_db}
    username: ${SPRING_DATASOURCE_USERNAME:ticket_user}
    password: ${SPRING_DATASOURCE_PASSWORD:root123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

app:
  jwt:
    secret: dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIHRpY2tldCBib29raW5nIHN5c3RlbSB3aXRoIFNwcmluZyBCb290IGFuZCBKV1Q=
    expiration-ms: 86400000
    refresh-expiration-ms: 2592000000
