server:
  port: 8085
spring:
  application:
    name: show-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_booking
    username: ticket_user
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
